const winningCombos = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [0, 4, 8],
    [2, 4, 6],
    [0, 3, 6],
    [1, 4, 7],
    [2, 5, 8]
];
let gameBoard = document.getElementById('game_board');
let emptySquares;
let newGameButton = document.getElementById('new_game');
let squares;
let squaresX;
let squaresO;

function setVariables() {
    emptySquares = [0, 1, 2, 3, 4, 5, 6, 7, 8];
    squaresX = [];
    squaresO = [];
}

function buildBoard() {
    for (let i = 0; i < 3; i++) { // build 3 rows
        let row = document.createElement('div');
        gameBoard.appendChild(row); // and append them to their parent div
        row.classList.add('row'); // add class 'row'
        if (i < 2) { // and for the first two rows
            row.classList.add('border_bottom'); // also add class 'border_bottom'
        }
        for (let j =0; j < 3; j++) { // build 3 columns
            let col = document.createElement('div');
            row.appendChild(col); // and append them to their parent div
            col.classList.add('col'); // add class 'col'
            if (j < 2) { // and for the first two columns
                col.classList.add('border_right'); // also add class 'border-right'
            }
        }
    }
    createIdsForColumns(); // add IDs to all columns
};

function createIdsForColumns() {
    for (let i = 0; i < 9; i++) { // create IDs numbered 0 to 8
        let col = document.getElementsByClassName('col'); // find all columns
        col[i].id = i; // and add an ID
    } 
};

function initGame() {
    gameBoard.innerHTML = ''; // clear the board
    setVariables(); // initialise all variables 
    buildBoard(); // display new board
    squares = Array.from(document.querySelectorAll('.col')); // create an array of 9 squares
    clickFunction(); 

    for (let i = 0; i < squares.length; i++) {
        squares[i].innerHTML = '';
    }
};

function pickRandomNumber() {
    let random = Math.floor(Math.random() * (emptySquares.length -1));
    return random;
};

function clickFunction() {
    // loop through all squares on board
    for (let i = 0; i < squares.length; i++) {
    // every time you click on a square
        squares[i].addEventListener('click', function() {
            // store the clicked element in a variable
            let elementClicked = squares[i];
            // change the elementClicked.id value into a number and store it to a variable
            const id = +elementClicked.id;
            // if number stored in id variable has already been removed from the array
            if (!emptySquares.includes(id)) {
                // stop running this function
                return
            }
            // otherwise, change the clicked element's innerHTML
            elementClicked.innerHTML = 'X';
            // and remove the id number from the array
            emptySquares = emptySquares.filter(num => num !== id);
            squaresX.push(id);
            checkForWinner();
            setTimeout(computersTurn, 700);
        })
    }
};

function computersTurn() {
    // pickRandomNumber function generates a random index number in our array
    // store random number from pickRandomNumber function in a variable
    let randomNumber = pickRandomNumber();
    // if you get to the last square, exit this function
    if (randomNumber === -1 || !emptySquares.length) {
        return;
    }
    // using the index number generated by pickRandomFunction, store the number at that position in our array in a variable
    let computersSquare = emptySquares[randomNumber];

    // change the randomly picked square's innerHTML to 'O'
    let compSquare = document.getElementById(computersSquare);
    if (!compSquare) {
        return
    }

    compSquare.innerHTML = 'O';
    // and remove that id from the array
    emptySquares = emptySquares.filter(num => num !== computersSquare);
    squaresO.push(computersSquare);

    checkForWinner();
};

function checkForWinner() {
    for (let i = 0; i < winningCombos.length; i++) {
        const winningCombo = winningCombos[i];
        xMatchesAll = winningCombo.every(num => squaresX.includes(num));
        oMatchesAll = winningCombo.every(num => squaresO.includes(num));
        if (xMatchesAll) {
            setTimeout(() => displayWinningScreen(true), 500);
            break;
        }
        if (oMatchesAll) {
            setTimeout(() => displayWinningScreen(false), 500);
            break;
        } 
    }
}


function displayWinningScreen(playerWins) {
    gameBoard.innerHTML = '';
    let newDiv = document.createElement('div');
    gameBoard.appendChild(newDiv);
    let winningMessage = document.createTextNode(`${playerWins ? 'You Win!' : 'You Lose!'}`);
    newDiv.appendChild(winningMessage);
    gameBoard.style.border = 'none';
    newDiv.style.fontSize = '100px';
    newDiv.style.color = 'red';
    newDiv.id = 'show';
}

newGameButton.addEventListener('click', initGame);

initGame()